"""The domain loop depends on this protocol, not on Playwright or DOM primitives."""

from typing import Protocol

from computer_use_replay.contracts import Condition, Step
from computer_use_replay.evidence import Snapshot


class Surface(Protocol):
    def bind_arguments(self, arguments: dict) -> None: ...

    async def navigate(self) -> None: ...
    async def observe(self) -> Snapshot: ...
    async def perform(self, step: Step, arguments: dict) -> str | None: ...
    async def condition(self, condition: Condition, arguments: dict) -> bool: ...
    def check_health(self) -> None: ...

    async def failure_screenshot(self) -> str | None: ...
